/**
 * @fileoverview gRPC-Web generated client stub for auth
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.31.0
// source: sign-up.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as sign$up_pb from './sign-up_pb'; // proto import: "sign-up.proto"
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"


export class SignUpManagerClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorInitiateSignUpAsync = new grpcWeb.MethodDescriptor(
    '/auth.SignUpManager/InitiateSignUpAsync',
    grpcWeb.MethodType.UNARY,
    sign$up_pb.InitiateSignUpRequest,
    google_protobuf_empty_pb.Empty,
    (request: sign$up_pb.InitiateSignUpRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  initiateSignUpAsync(
    request: sign$up_pb.InitiateSignUpRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  initiateSignUpAsync(
    request: sign$up_pb.InitiateSignUpRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  initiateSignUpAsync(
    request: sign$up_pb.InitiateSignUpRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/auth.SignUpManager/InitiateSignUpAsync',
        request,
        metadata || {},
        this.methodDescriptorInitiateSignUpAsync,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/auth.SignUpManager/InitiateSignUpAsync',
    request,
    metadata || {},
    this.methodDescriptorInitiateSignUpAsync);
  }

  methodDescriptorVerifyAndSignUpAsync = new grpcWeb.MethodDescriptor(
    '/auth.SignUpManager/VerifyAndSignUpAsync',
    grpcWeb.MethodType.UNARY,
    sign$up_pb.VerifyAndSignUpRequest,
    google_protobuf_empty_pb.Empty,
    (request: sign$up_pb.VerifyAndSignUpRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  verifyAndSignUpAsync(
    request: sign$up_pb.VerifyAndSignUpRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  verifyAndSignUpAsync(
    request: sign$up_pb.VerifyAndSignUpRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  verifyAndSignUpAsync(
    request: sign$up_pb.VerifyAndSignUpRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/auth.SignUpManager/VerifyAndSignUpAsync',
        request,
        metadata || {},
        this.methodDescriptorVerifyAndSignUpAsync,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/auth.SignUpManager/VerifyAndSignUpAsync',
    request,
    metadata || {},
    this.methodDescriptorVerifyAndSignUpAsync);
  }

  methodDescriptorIsEmailTakenAsync = new grpcWeb.MethodDescriptor(
    '/auth.SignUpManager/IsEmailTakenAsync',
    grpcWeb.MethodType.UNARY,
    sign$up_pb.IsEmailTakenRequest,
    sign$up_pb.IsEmailTakenReply,
    (request: sign$up_pb.IsEmailTakenRequest) => {
      return request.serializeBinary();
    },
    sign$up_pb.IsEmailTakenReply.deserializeBinary
  );

  isEmailTakenAsync(
    request: sign$up_pb.IsEmailTakenRequest,
    metadata?: grpcWeb.Metadata | null): Promise<sign$up_pb.IsEmailTakenReply>;

  isEmailTakenAsync(
    request: sign$up_pb.IsEmailTakenRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: sign$up_pb.IsEmailTakenReply) => void): grpcWeb.ClientReadableStream<sign$up_pb.IsEmailTakenReply>;

  isEmailTakenAsync(
    request: sign$up_pb.IsEmailTakenRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: sign$up_pb.IsEmailTakenReply) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/auth.SignUpManager/IsEmailTakenAsync',
        request,
        metadata || {},
        this.methodDescriptorIsEmailTakenAsync,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/auth.SignUpManager/IsEmailTakenAsync',
    request,
    metadata || {},
    this.methodDescriptorIsEmailTakenAsync);
  }

}

