/**
 * @fileoverview gRPC-Web generated client stub for auth
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.31.0
// source: sign-up.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as sign$up_pb from './sign-up_pb'; // proto import: "sign-up.proto"
import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb'; // proto import: "google/protobuf/empty.proto"


export class SignUpServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorInitiateSignUpAsync = new grpcWeb.MethodDescriptor(
    '/auth.SignUpService/InitiateSignUpAsync',
    grpcWeb.MethodType.UNARY,
    sign$up_pb.InitiateSignUpRequest,
    sign$up_pb.InitiateSignUpResponse,
    (request: sign$up_pb.InitiateSignUpRequest) => {
      return request.serializeBinary();
    },
    sign$up_pb.InitiateSignUpResponse.deserializeBinary
  );

  initiateSignUpAsync(
    request: sign$up_pb.InitiateSignUpRequest,
    metadata?: grpcWeb.Metadata | null): Promise<sign$up_pb.InitiateSignUpResponse>;

  initiateSignUpAsync(
    request: sign$up_pb.InitiateSignUpRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: sign$up_pb.InitiateSignUpResponse) => void): grpcWeb.ClientReadableStream<sign$up_pb.InitiateSignUpResponse>;

  initiateSignUpAsync(
    request: sign$up_pb.InitiateSignUpRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: sign$up_pb.InitiateSignUpResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/auth.SignUpService/InitiateSignUpAsync',
        request,
        metadata || {},
        this.methodDescriptorInitiateSignUpAsync,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/auth.SignUpService/InitiateSignUpAsync',
    request,
    metadata || {},
    this.methodDescriptorInitiateSignUpAsync);
  }

  methodDescriptorVerifyAndSignInAsync = new grpcWeb.MethodDescriptor(
    '/auth.SignUpService/VerifyAndSignInAsync',
    grpcWeb.MethodType.UNARY,
    sign$up_pb.VerifyAndSignInRequest,
    google_protobuf_empty_pb.Empty,
    (request: sign$up_pb.VerifyAndSignInRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  verifyAndSignInAsync(
    request: sign$up_pb.VerifyAndSignInRequest,
    metadata?: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  verifyAndSignInAsync(
    request: sign$up_pb.VerifyAndSignInRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  verifyAndSignInAsync(
    request: sign$up_pb.VerifyAndSignInRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/auth.SignUpService/VerifyAndSignInAsync',
        request,
        metadata || {},
        this.methodDescriptorVerifyAndSignInAsync,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/auth.SignUpService/VerifyAndSignInAsync',
    request,
    metadata || {},
    this.methodDescriptorVerifyAndSignInAsync);
  }

}

