version: 0.0
os: linux

# EC2/On-Prem deployment – lifecycle hooks only (files are copied implicitly)
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      runas: root
  AfterInstall:
    - location: scripts/after-install.sh
      runas: root
  ApplicationStart:
    - location: scripts/application-start.sh
      runas: root
  ValidateService:
    - location: scripts/validate-service.sh
      runas: root
