name: {{ PASCALCASE_SERVICE_NAME }} Debug Build

on:
  pull_request:
    type:
      - opened
      - reopened
      - edited
    branches:
      - 'main
      - 'integration/*'
    paths:
      - 'Microservices/{{ PASCALCASE_SERVICE_NAME }}/**'
      - '.github/workflows/{{ SERVICE_NAME }}-debug.yml'
jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Microservices/{{ PASCALCASE_SERVICE_NAME }}/
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
