version: "3.8"

services:
  app:
    image: $IMAGE_URI
    environment:
      ASPNETCORE_URLS: https://+:443
      ASPNETCORE_ENVIRONMENT: Production
    networks:
      - net
    secrets:
      - source: cert_pfx
        target: /https/aspnetapp.pfx
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 15s
        order: stop-first
networks:
  net:
    name: ${NETWORK_NAME}
    external: true

secrets:
  cert_pfx:
    name: ${CERT_PFX_SECRET_NAME}
    external: true