version: "3.8"

services:
  app:
    image: $IMAGE_NAME
    environment:
      ASPNETCORE_URLS: https://+:443
      ASPNETCORE_ENVIRONMENT: Development
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE
      Shared_Secrets__UseDevOverrides: 'true'
      Shared_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      COGNITO_CONFIRMED_USERS_COUNT: ${COGNITO_CONFIRMED_USERS_COUNT}
    volumes:
      # Bind AWS credentials directory
      - type: bind
        source: $HOME/.aws
        target: /home/app/.aws
    networks:
      - net
    secrets:
      - source: aspnetapp.pfx
        target: /https/aspnetapp.pfx
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 15s
        order: stop-first
networks:
  net:
    external: true

secrets:
  aspnetapp.pfx:
    external: true