version: "3.8"

services:
  app:
    image: $IMAGE_URI
    environment:
      ASPNETCORE_URLS: http://+:443
      ASPNETCORE_ENVIRONMENT: Production
      AWS_REGION: ${AWS_REGION}
      COGNITO_CONFIRMED_USERS_COUNT: ${COGNITO_CONFIRMED_USERS_COUNT}
    networks:
      - net
    deploy:
      labels:
        version: ${VERSION}
        service: ${SERVICE_NAME}
        environment: ${ENVIRONMENT}
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - engine.labels.worker_type == compute
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 15s
        order: stop-first
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
networks:
  net:
    name: ${NETWORK_NAME}
    external: true

configs:
  envoy_config:
    name:  ${SERVICE_NAME}_envoy_config_${VERSION}
    external: true
  envoy_clusters:
    name: ${SERVICE_NAME}_envoy_cds_config_${VERSION}
    external: true
  envoy_routes:
    name: ${SERVICE_NAME}_envoy_rds_config_${VERSION}
    external: true