version: "3.8"

services:
  app:
    image: $IMAGE_NAME
    env_file:
      - ${ENV_FILE}
      - ${OVERRIDE_ENV_FILE}
    environment:
      ASPNETCORE_URLS: https://+:8000
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: $CERTIFICATE_PASSWORD
    networks:
      - net
    secrets:
      - source: aspnetapp.pfx
        target: /https/aspnetapp.pfx
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 15s
        order: stop-first
networks:
  net:
    external: true

secrets:
  aspnetapp.pfx:
    external: true