version: "3.8"

services:
  app:
    image: $IMAGE_NAME
    env_file:
      - ${ENV_FILE}
      - ${OVERRIDE_STAGING_ENV_FILE}
    environment:
      ASPNETCORE_URLS: https://+:443
      ASPNETCORE_ENVIRONMENT: Staging
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${CERTIFICATE_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    volumes:
      - $CERTIFICATE_PATH:/https:ro
    networks:
      - net
    ports:
      - "10000:443"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 15s
        order: stop-first
networks:
  net:
    external: true