version: "3.8"

services:
  app:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - net
    volumes:
      - redis_data:/data
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 15s
        order: stop-first

networks:
  net:
    external: true

volumes:
  redis_data:
    driver: local