version: "3.8"

services:
  app:
    image: amazon/dynamodb-local:latest
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/home/dynamodblocal/data"]
    ports:
      - "8000:8000"
    networks:
      - net
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    user: "0:0"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 15s
        order: stop-first

networks:
  net:
    external: true

volumes:
  dynamodb_data:
    driver: local


