version: "3.8"

services:
  app:
    image: authentication-sample/postgres:latest
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    command: [
      "postgres",
      "-c", "shared_preload_libraries=pg_cron",
      "-c", "cron.database_name=$DATABASE_NAME"
    ]
    ports:
      - "5432:5432"
    networks:
      - net
    volumes:
      - db_data:/var/lib/postgresql/data
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 15s
        order: stop-first
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers/server.json
    volumes:
      - $PGADMIN_PATH:/pgadmin4/servers
    networks:
      - net
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 15s
        order: stop-first
networks:
  net:
    external: true
volumes:
  db_data:
    driver: local