name: 'Authentication Service Deployment'

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment'
        required: true
        type: choice
        options:
          - staging
          - production
        default: 'production'

  # Automatic trigger on service changes
  push:
    branches: [ main ]
    paths:
      - 'Microservices/Authentication/**'
      - '.github/workflows/authentication-service.yml'

env:
  SERVICE_NAME: 'authentication'
  
permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: 'Deploy Authentication Service'
    uses: ./.github/workflows/templates/deploy-microservice.yml
    with:
      service_name: 'authentication'
      environment: ${{ github.event.inputs.environment || 'staging' }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPOSITORY_PREFIX: ${{ vars.APP_NAME }}
      DEPLOYMENT_BUCKET: ${{ secrets.DEPLOYMENT_BUCKET }} 